# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 14:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('article_cover', models.ImageField(default='./article/defaultpic.jpg', upload_to='./article/%Y/%m%d/', verbose_name='文章封面')),
                ('article_abstract', models.CharField(max_length=128, verbose_name='文章摘要')),
                ('article_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章详情')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('view_times', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_notice', models.BooleanField(default=False, help_text='如果为True, 在首页公告显示', verbose_name='开启公告')),
                ('is_case', models.BooleanField(default=False, verbose_name='经典案例')),
                ('is_business_evaluation', models.BooleanField(default=False, verbose_name='阿里商评')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='小研推荐')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='InformationClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name_en', models.CharField(max_length=128, verbose_name='资讯分类en')),
                ('info_name_cn', models.CharField(max_length=128, verbose_name='资讯分类cn')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
            },
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_category_name_en', models.CharField(max_length=128, verbose_name='链接分类en')),
                ('link_category_name_cn', models.CharField(max_length=128, verbose_name='链接分类cn')),
            ],
            options={
                'verbose_name': '链接分类',
                'verbose_name_plural': '链接分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_en', models.CharField(max_length=128, verbose_name='标签en')),
                ('tag_name_cn', models.CharField(max_length=128, verbose_name='标签cn')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_information_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.InformationClassification', verbose_name='资讯分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='article_set', to='app01.Tag', verbose_name='标签'),
        ),
    ]
