# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 10:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20180830_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('abstract', models.CharField(max_length=30, verbose_name='摘要')),
                ('article_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章详情')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
    ]
