# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20190413_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='mwordId',
            field=models.IntegerField(default=1, verbose_name='mworkid'),
        ),
    ]
