# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20190414_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IOPoints',
        ),
    ]
