# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20190416_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iopoints',
            options={'ordering': ['IOPointsId'], 'verbose_name': '所有机器监测点', 'verbose_name_plural': '所有机器监测点'},
        ),
        migrations.AlterModelTable(
            name='iopoints',
            table='所有机器监测点',
        ),
    ]
