# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_users_article_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='article_cover',
            new_name='userTou',
        ),
    ]
