# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180820_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
    ]
