# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_article_article_cover_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_cover_sm',
            field=models.ImageField(default='./article/defaultpic_sm.jpg', upload_to='./article/%Y/%m%d/', verbose_name='文章封面'),
        ),
    ]
