# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_delete_iopoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOPoints',
            fields=[
                ('IOPointsId', models.AutoField(primary_key=True, serialize=False, verbose_name='机器监测点id')),
                ('minRange', models.IntegerField(blank=True, default=0, null=True, verbose_name='最小量程')),
                ('maxRange', models.IntegerField(verbose_name='最小量程')),
                ('aline', models.IntegerField(blank=True, null=True, verbose_name='最小量程')),
                ('method', models.IntegerField(blank=True, default=1, null=True, verbose_name='最小量程')),
            ],
        ),
        migrations.AlterField(
            model_name='gateways_all',
            name='gatewayName',
            field=models.CharField(max_length=30, unique=True, verbose_name='网关名'),
        ),
        migrations.AlterField(
            model_name='iopoints_all',
            name='IOPName',
            field=models.CharField(max_length=30, unique=True, verbose_name='监测点名'),
        ),
        migrations.AddField(
            model_name='iopoints',
            name='machineGateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.gateways_all', verbose_name='网关'),
        ),
        migrations.AddField(
            model_name='iopoints',
            name='machineName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.machines', verbose_name='机器名'),
        ),
    ]
