# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20190416_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='iopoints',
            name='physicalName',
            field=models.CharField(default='主温度', max_length=16, verbose_name='机器监测点物理名称'),
            preserve_default=False,
        ),
    ]
