# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_iopoints_physicalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iopoints',
            name='physicalName',
            field=models.CharField(max_length=16, unique=True, verbose_name='机器监测点物理名称'),
        ),
    ]
