# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alarmcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmcodes',
            name='machineName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.machines', verbose_name='机器名'),
        ),
    ]
