# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_singlealarmcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmSolutons',
            fields=[
                ('alarmSolutonId', models.AutoField(primary_key=True, serialize=False, verbose_name='解决方案id')),
                ('alarmSolutonName', models.CharField(max_length=16, unique=True, verbose_name='解决方案名称')),
                ('alarmSolutonDetail', models.CharField(max_length=32, verbose_name='解决方案描述')),
                ('alarmCodeList', models.CharField(max_length=16, verbose_name='适用与异常码/组合码')),
            ],
            options={
                'verbose_name': '解决方案',
                'verbose_name_plural': '解决方案',
                'db_table': '解决方案',
                'ordering': ['alarmSolutonId'],
            },
        ),
    ]
