# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_auto_20190420_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsolutons',
            name='alarmCodeList',
            field=models.TextField(verbose_name='适用与异常码/组合码'),
        ),
    ]
