# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_auto_20190420_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmprocesshistory',
            name='machineName',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='机器名称'),
        ),
    ]
