# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_auto_20190424_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='用户状态'),
        ),
    ]
