# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_auto_20200401_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseevaluate',
            name='id',
        ),
        migrations.AddField(
            model_name='courseevaluate',
            name='courseEvaluateDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评价时间'),
        ),
        migrations.AddField(
            model_name='courseevaluate',
            name='courseEvaluateId',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='课程评价id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseevaluate',
            name='grade',
            field=models.FloatField(default=5, verbose_name='评分'),
        ),
    ]
