# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_auto_20200403_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevaluate',
            name='courseEvaluateMsg',
            field=models.TextField(max_length=200, null=True, verbose_name='课程评价'),
        ),
    ]
