# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_auto_20200404_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hutprojectsusers',
            name='hutNotice',
        ),
        migrations.AddField(
            model_name='hutnotice',
            name='hutNoticeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.hutProjectsUsers', verbose_name='通知人'),
            preserve_default=False,
        ),
    ]
