# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_auto_20200407_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutnotice',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='通知状态'),
        ),
    ]
