# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-10 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_auto_20200407_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseevaluate',
            options={'ordering': ('-courseEvaluateDate',), 'verbose_name': '湖工大软件工程系统课程评价', 'verbose_name_plural': '湖工大软件工程系统课程评价'},
        ),
    ]
