# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_abstract',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='文章摘要'),
        ),
    ]
