# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180821_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('email', models.EmailField(max_length=26, verbose_name='邮箱')),
                ('message', models.TextField(max_length=200, verbose_name='信息')),
            ],
            options={
                'verbose_name': '简历邮箱信息',
                'verbose_name_plural': '简历邮箱信息',
            },
        ),
    ]
