# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20190416_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmCodes',
            fields=[
                ('alarmCodeId', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='异常码id')),
                ('alarmCodeName', models.CharField(max_length=16, verbose_name='异常码名字')),
                ('minValue', models.IntegerField(default=0, verbose_name='最小值')),
                ('maxValue', models.IntegerField(verbose_name='最大值')),
                ('alarmMsg', models.CharField(blank=True, max_length=36, null=True, verbose_name='异常信息')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='异常级别')),
                ('timeLimit', models.IntegerField(blank=True, default=10, null=True, verbose_name='异常时延')),
                ('machineName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.machines', unique=True, verbose_name='机器名')),
                ('physicalName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.IOPoints', verbose_name='监控点物理量')),
            ],
            options={
                'verbose_name': '异常码',
                'verbose_name_plural': '异常码',
                'db_table': '异常码',
                'ordering': ['alarmCodeId'],
            },
        ),
    ]
