# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_auto_20190424_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='article_cover',
            field=models.ImageField(default='./user/defaultTou.png', upload_to='./user/%Y/%m%d/', verbose_name='用户头像'),
        ),
    ]
