# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_auto_20190425_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseEvaluate',
            fields=[
                ('courseEvaluateId', models.AutoField(primary_key=True, serialize=False, verbose_name='课程评价id')),
                ('courseEvaluateMsg', models.TextField(max_length=200, null=True, verbose_name='课程评价')),
                ('grade', models.FloatField(default=5, verbose_name='评分')),
                ('courseEvaluateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评价时间')),
            ],
            options={
                'verbose_name': '湖工大软件工程系统课程评价',
                'verbose_name_plural': '湖工大软件工程系统课程评价',
                'db_table': '湖工大软件工程系统课程评价',
                'ordering': ('-courseEvaluateDate',),
            },
        ),
        migrations.CreateModel(
            name='hutCourse',
            fields=[
                ('hutCourseId', models.AutoField(primary_key=True, serialize=False, verbose_name='课程id')),
                ('hutCourseName', models.CharField(max_length=16, verbose_name='课程名')),
                ('hutCourseDescribe', models.CharField(max_length=16, verbose_name='课程描述')),
                ('hutCourseTeacher', models.CharField(max_length=16, verbose_name='任课老师')),
            ],
            options={
                'verbose_name': '湖工大软件工程系统课程信息',
                'verbose_name_plural': '湖工大软件工程系统课程信息',
                'db_table': '湖工大软件工程系统课程信息',
            },
        ),
        migrations.CreateModel(
            name='hutNotice',
            fields=[
                ('hutNoticeId', models.AutoField(primary_key=True, serialize=False, verbose_name='通知id')),
                ('msg', models.TextField(max_length=200, verbose_name='通知内容')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='通知状态')),
                ('courseEvaluateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('byPerson', models.CharField(default='lin', max_length=10, verbose_name='发布通知者')),
            ],
            options={
                'verbose_name': '湖工大软件工程系统通知',
                'verbose_name_plural': '湖工大软件工程系统通知',
                'db_table': '湖工大软件工程系统通知',
            },
        ),
        migrations.CreateModel(
            name='hutProjectsUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('userName', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('userTou', models.ImageField(default='./hutUser/defaultTou.png', upload_to='./hutUser/%Y/%m%d/', verbose_name='用户头像')),
                ('jurisdiction', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1, verbose_name='权限等级')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='用户状态')),
                ('remarks', models.CharField(max_length=10, verbose_name='remarks')),
            ],
            options={
                'verbose_name': '湖工大软件工程系统用户',
                'verbose_name_plural': '湖工大软件工程系统用户',
                'db_table': '湖工大软件工程系统用户',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='hutnotice',
            name='hutNoticeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.hutProjectsUsers', verbose_name='通知人'),
        ),
        migrations.AddField(
            model_name='courseevaluate',
            name='hutCourseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hutCourseId_courseId', to='app01.hutCourse', verbose_name='课程id'),
        ),
        migrations.AddField(
            model_name='courseevaluate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hutProjectsUsersId', to='app01.hutProjectsUsers', verbose_name='用户id'),
        ),
    ]
